"""Application configuration management using Pydantic Settings.

This module defines the central `Settings` class that loads, validates, and caches
environment variables across database connections, Redis pub/sub brokers, Celery queues,
storage directories, LLM credentials, and JWT authentication policies.
"""

from functools import lru_cache
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Global configuration settings for the DocFlow application.

    Attributes:
        app_name: Display name for the application and OpenAPI documentation.
        environment: Deployment environment ("development", "staging", "production").
        secret_key: Cryptographic secret key used for signing JWT access tokens.
        database_url: Async SQLAlchemy PostgreSQL connection URI (asyncpg driver).
        sync_database_url: Synchronous SQLAlchemy connection URI for Celery workers (psycopg2).
        redis_url: Redis URI used for application caching and pub/sub event streams.
        celery_broker_url: Redis broker URL for Celery asynchronous task distribution.
        celery_result_backend: Redis backend URL for Celery task result persistence.
        upload_dir: Local filesystem directory for staging uploaded documents.
        max_file_size_mb: Maximum permitted upload payload size in megabytes.
        allowed_extensions: List of supported file extensions for ingestion.
        cors_origins: Whitelist of origins permitted to make cross-origin requests.
        pubsub_channel_prefix: Namespace prefix for Redis pub/sub job event channels.
        sse_mode: Real-time update strategy ("pubsub" for Redis, or "poll" for database polling).
        sse_poll_interval: Interval in seconds between status checks when polling.
        sse_timeout: Maximum duration in seconds before an idle SSE stream closes.
        gemini_api_key: API key for Google Gemini model inference and embeddings.
        llm_provider: Active LLM provider identifier (defaults to "gemini").
        llm_model: Target Gemini model name for metadata extraction and agent reasoning.
        llm_request_timeout_seconds: Request timeout in seconds for LLM API calls.
        llm_max_output_tokens: Maximum completion tokens generated by the LLM.
        llm_max_input_characters: Upper limit of raw characters sent in prompt context.
        embedding_model: Gemini model identifier used for generating text embeddings.
        embedding_dimensions: Vector dimension produced by the embedding model.
        embedding_batch_size: Maximum text chunks embedded per API request batch.
        rag_max_answer_tokens: Maximum token budget for single-document RAG answers.
        jwt_algorithm: Cryptographic algorithm used for JWT token generation.
        jwt_access_token_expire_minutes: Lifetime of issued JWT access tokens in minutes.
    """

    app_name: str = "DocFlow"
    environment: str = "development"
    secret_key: str = "supersecretkey_change_in_production"

    database_url: str = "postgresql+asyncpg://docflow:docflow_secret@postgres:5432/docflow_db"
    sync_database_url: str = "postgresql+psycopg2://docflow:docflow_secret@postgres:5432/docflow_db"

    redis_url: str = "redis://redis:6379/0"
    celery_broker_url: str = "redis://redis:6379/1"
    celery_result_backend: str = "redis://redis:6379/2"

    upload_dir: str = "/app/uploads"
    max_file_size_mb: int = 50
    allowed_extensions: list[str] = ["pdf", "txt", "csv", "json", "md", "docx"]

    cors_origins: list[str] = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "https://async-document-processing.vercel.app",
    ]

    pubsub_channel_prefix: str = "job_events"

    sse_mode: str = "pubsub"
    sse_poll_interval: float = 1.5
    sse_timeout: int = 75

    gemini_api_key: str | None = None
    llm_provider: str = "gemini"
    llm_model: str = "gemini-3.1-flash-lite"
    llm_request_timeout_seconds: int = 30
    llm_max_output_tokens: int = 1024
    llm_max_input_characters: int = 60000

    embedding_model: str = "gemini-embedding-2"
    embedding_dimensions: int = 768
    embedding_batch_size: int = 20
    rag_max_answer_tokens: int = 512

    jwt_algorithm: str = "HS256"
    jwt_access_token_expire_minutes: int = 60 * 24

    model_config = SettingsConfigDict(env_file=".env", case_sensitive=False)


@lru_cache()
def get_settings() -> Settings:
    """Instantiate and cache application settings singleton.

    Returns:
        Settings: Cached configuration instance populated from environment variables.
    """
    return Settings()


settings = get_settings()
